# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 4
create_project -in_memory -part xc7a35tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/monx/Projects/FIFO_USB/USB_FIFO.cache/wt [current_project]
set_property parent.project_path /home/monx/Projects/FIFO_USB/USB_FIFO.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part trenz.biz:te0711_35_2c:part0:1.0 [current_project]
set_property ip_output_repo /home/monx/Projects/FIFO_USB/USB_FIFO.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/monx/Projects/FIFO_USB/USB_FIFO.srcs/sources_1/bd/design_2/hdl/design_2_wrapper.v
read_vhdl -library xil_defaultlib {
  /home/monx/Projects/FIFO_USB/USB_FIFO.srcs/sources_1/new/Data_generator.vhd
  /home/monx/Projects/FIFO_USB/USB_FIFO.srcs/sources_1/imports/new/ram.vhd
  /home/monx/Projects/FIFO_USB/USB_FIFO.srcs/sources_1/imports/new/MPairStorageController.vhd
  /home/monx/Projects/FIFO_USB/USB_FIFO.srcs/sources_1/new/USB_FIFO.vhd
}
add_files /home/monx/Projects/FIFO_USB/USB_FIFO.srcs/sources_1/bd/design_2/design_2.bd
set_property used_in_implementation false [get_files -all /home/monx/Projects/FIFO_USB/USB_FIFO.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/monx/Projects/FIFO_USB/USB_FIFO.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/monx/Projects/FIFO_USB/USB_FIFO.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/monx/Projects/FIFO_USB/USB_FIFO.srcs/sources_1/bd/design_2/design_2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/monx/Projects/FIFO_USB/USB_FIFO.srcs/constrs_1/imports/REVO/REVO1.xdc
set_property used_in_implementation false [get_files /home/monx/Projects/FIFO_USB/USB_FIFO.srcs/constrs_1/imports/REVO/REVO1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_2_wrapper -part xc7a35tcsg324-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_2_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_2_wrapper_utilization_synth.rpt -pb design_2_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
