# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/REVO/REVO1.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UART_TX_0_0/design_1_UART_TX_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_UART_TX_0_0 || ORIG_REF_NAME==design_1_UART_TX_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UART_RX_0_0/design_1_UART_RX_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_UART_RX_0_0 || ORIG_REF_NAME==design_1_UART_RX_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1_0 || ORIG_REF_NAME==design_1_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_MPairStorageControll_0_0/design_1_MPairStorageControll_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_MPairStorageControll_0_0 || ORIG_REF_NAME==design_1_MPairStorageControll_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Data_generator_0_0/design_1_Data_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Data_generator_0_0 || ORIG_REF_NAME==design_1_Data_generator_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
