# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/themo/OneDrive/Desktop/REVO/V/Final/Simulation and Bench marking/USB_FIFO/USB_FIFO.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0.xci
# IP: The module: 'design_2_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/themo/OneDrive/Desktop/REVO/V/Final/Simulation and Bench marking/USB_FIFO/USB_FIFO.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/themo/OneDrive/Desktop/REVO/V/Final/Simulation and Bench marking/USB_FIFO/USB_FIFO.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/themo/OneDrive/Desktop/REVO/V/Final/Simulation and Bench marking/USB_FIFO/USB_FIFO.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/themo/OneDrive/Desktop/REVO/V/Final/Simulation and Bench marking/USB_FIFO/USB_FIFO.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0.xci
# IP: The module: 'design_2_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/themo/OneDrive/Desktop/REVO/V/Final/Simulation and Bench marking/USB_FIFO/USB_FIFO.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/themo/OneDrive/Desktop/REVO/V/Final/Simulation and Bench marking/USB_FIFO/USB_FIFO.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/themo/OneDrive/Desktop/REVO/V/Final/Simulation and Bench marking/USB_FIFO/USB_FIFO.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
